name: 'update doc'

on:
  workflow_call:
    inputs:
      source-path:
        default: './src/**/*.ts'
        required: false
        type: string

permissions:
  contents: write

jobs:
  update-doc:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 20.x

      - name: Install
        run: npm install typedoc typedoc-plugin-markdown @ysk8hori/typescript-graph -g

      - name: Documents Update
        run: |
          typedoc --plugin typedoc-plugin-markdown ${{ inputs.source-path }}
          tsg --md dependencies.md

      - name: Commit & Push
        run: |
          git config --local user.email "github-actions@github.com"
          git config --local user.name "github-actions"
          git add ./docs ./dependencies.md
          git commit -m "Document Auto Update"
          git push origin main
